### ISSUE TITLE
Add column for new zooplankton biomass method

### ISSUE THREAD

**Issue by mhidas** [aodn/public-schema#11]
A second methodology for zooplankton biomass is being tested at CSIRO (mostly for Darwin, because of sand). The results will be added as an additional biomass column in the `bgc_trip` table. We have agreed to hold off on making this change in this repo until the plankton product code (#5) has been merged and the other BGC and CPR raw data have been set up (#7 and #10).

**Comment by clairedavies** [comment]
I have added this column to the export, this will come through when Steve runs an update (which he will wait for you to be ready for). I have included this information in the product specifications. Note, there are very few records at this time as we have only just started doing this new method.

**Comment by mhidas** [comment]
@clairedavies Thanks. As agreed, let's hold off on this change until we've got some of the other pending changes reviewed and merged. In fact the zooplankton products will now be done in a separate PR (#12) that @leonardolaiolo just started working on, so let's come back to this after that PR has been merged.

**Comment by mhidas** [comment]
Done
