### ISSUE TITLE
Add CTD-derived parameters to plankton products

### ISSUE THREAD

**Issue by mhidas** [aodn/public-schema#13]
The Plankton products specification lists three parameters derived from CTD casts, to be included in every plankton product:

Name | Description
-- | --
CTDSST_degC | Temperature of the water column near the surface, from matching CTD cast
CTDChlaSurf_mgm3 | Artificial chlorophyll concentration computed from bio-optical sensor on matching CTD cast
CTDSalinity_psu | Derived salinity

These will be most easily added when/after we create the "Depth-binned CTD" product.

**Comment by mhidas** [comment]
@clairedavies I am now working on extracting these "surface" values from the CTD profiles. In the catch-up meeting you said we should take the value at 10m. The easiest way to pick that value out is to choose the row where the depth (rounded to integer) is exactly 10. This works for almost all the trips with a matching CTD cast.

Currently there are about 10 trips where the closest available data is at a greater depth, ranging from 11m up to 60m. Where do we draw the line?

**Comment by mhidas** [comment]
Also, what shall we do about the QC flags? Each value in the CTD profile has its own QC flag. Sometimes there are reasonable-looking numbers (e.g. temperature = 15.5), but the QC flag is 4 = "bad data".
Should we replace the value with a null in such a case?
And also for flag of 3 = "Bad_data_that_are_potentially_correctable"?
What about flag of 0 = "No_QC_performed"?

**Comment by clairedavies** [comment]
> Currently there are about 10 trips where the closest available data is at a greater depth, ranging from 11m up to 60m. Where do we draw the line?

I would say at 5m, shallower than that is often unstable and above that is not surface. Leave these blank.

**Comment by clairedavies** [comment]
> Also, what shall we do about the QC flags? Each value in the CTD profile has its own QC flag. Sometimes there are reasonable-looking numbers (e.g. temperature = 15.5), but the QC flag is 4 = "bad data". Should we replace the value with a null in such a case? And also for flag of 3 = "Bad_data_that_are_potentially_correctable"? What about flag of 0 = "No_QC_performed"?

It might be worth asking someone who knows about CTDs, maybe Guillaume has a better idea of what is acceptable for CTD data and what users would expect.

**Comment by mhidas** [comment]
> I would say at 5m, shallower than that is often unstable and above that is not surface. Leave these blank.

Thanks @clairedavies . Just to clarify, do you mean _within 5m_ of the 10m target? i.e. only take values measure between depths of 5m an 15m?

**Comment by clairedavies** [comment]
yes

**Comment by mhidas** [comment]
I had a quick chat to Guillaume about the qc flags, and we agreed that we should not include values that have been flagged as 3 or 4. We'll leave the flag 0 (not QC'd) values.

**Comment by clairedavies** [comment]
That’s fine by me.
