### ISSUE TITLE
Raw data for BGC combined and Larval Fish products 

### ISSUE THREAD

**Issue by leonardolaiolo** [aodn/public-schema#14]
This is related to the Raw data for BGC combined and Larval Fish products. 
In Steve [PR](https://github.com/aodn/public-schema/pull/7) was highlighted that:
```
Still to resolve:
• missing data (nulls) in SAMPLEDEPTH_M and REPLICATE columns.
• appropriate flag value in SAMPLEDEPTH_M (currently "WC" - not numeric)
```

**Comment by mhidas** [comment]
These issues have been resolved.
