### ISSUE TITLE
Timezone conversions UTC/Local

### ISSUE THREAD

**Issue by mhidas** [aodn/public-schema#3]
For most products, it we want to provide sample times in both UTC and local time. At CSIRO, the time zone conversion is done based on just the timestamp and latitude/longitude of the sample (using R code (?)).

However, it would be slightly more efficient to only harvest one set of timestamps (i.e. only UTC _or_ local) from CSIRO to AODN, then calculate the other timezone at AODN. The best way to do this is yet to be determined.

This will need to be done for both fixed-station (NRS, etc) and ship-track (CPR) products so having a fixed table of timezones for each station would only be a partial solution.

**Comment by mhidas** [comment]
Original discussion from [pull request #2](https://github.com/aodn/public-schema/pull/2#discussion_r661962247) (referring to the `SAMPLEDATELOCAL` column in `bgc_trip` table):

> @mhidas 
For the purpose of matching up these trips with the CTD profiles we have, it would be helpful to have the UTC time instead (or as well).
 
> @clairedavies 
I thought we agreed to code all the local to UTC times save them both being kept in all files.
 
> @mhidas
Ok, but we currently don't have any timezone info. To do the conversion, we would need to have the relevant timezone for each station in the bgc_stationinfo table (I think it was there at some point, but has been removed?).
Alternatively, timezones could be included in every single value of SAMPLEDATELOCAL. Pretty sure the format in the spec allows it to be included (though harvesting such timestamps might be a bit more error prone...).
 
> @clairedavies 
So the lat & long & date are normally all you need to code the UTC time, the packages know the timezones. I'm not sure how you are intending on doing this though.
 
> @mhidas 
Our intention for now is to harvest all your raw tables unchanged into our (Postgresql) database and do all AODN-side processing in there, i.e. in SQL. I had a bit of a look yesterday, and couldn't find any postgresql functions that could do timezone conversions based on just lat/lon - the available functions require a specific timezone name ('Australia/Hobart', or 'AEST') as an argument.
It may be possible to do what you suggest in Python but that will require us to modify the data before ingest. I can look into that, but I think it would be easiest to just add the timezone for each station in bgc_stationinfo...

> @clairedavies 
I don't actually have time zones recorded, I only produce them through code. I have the state code for the NRS stations if that will that help? But then that gets more complicated for CPR. Or I can just provide local and utc time if that makes things easier. That's fairly inefficient but at least it can be automatic in the database for NRS and CPR.

**Comment by leonardolaiolo** [comment]
CSIRO does all the conversions
