### ISSUE TITLE
bgc_trip missing entry for trip_code DAR20110627

### ISSUE THREAD

**Issue by mhidas** [aodn/public-schema#4]
Both bgc_phyto_raw and bgc_zoop_raw have data for this trip code, but there's no associated metadata in the bgc_trip table.

(All tables downloaded 2021-07-28 15:38)

**Comment by clairedavies** [comment]
This trip, DAR20110627, is in imos_web2.bgc_trip. Steve, I'm not sure what is happening here and why Marty can't see it. Can you check it is in your geoserver layer please.

**Comment by mhidas** [comment]
I have just confirmed that the trip_code DAR20110627 is now included in the `bgc_trip` table. As discussed in the catch-up this morning, this must have been a temporary out-of-sync state.
