### ISSUE TITLE
SampleDate_Local header not consistent

### ISSUE THREAD

**Issue by clairedavies** [aodn/public-schema#43]
Ensure all headers are SampleDate_Local 

Needs changing in the BGC products. 
Plankton products are good.

**Comment by jaseeverett** [comment]
@clairedavies I think you mean the other way around. Uppercase `_Local` is used in the bcc products, but lowercase `_local` is in the plankton products. So I think the plankton products need to be updated to make them all uppercase.

**Comment by jaseeverett** [comment]
A check of all the date and time fields for all files is needed to ensure consistency of Local/local. 
* In the bcc/nrs plankton data lower case "_l" is used for SampleTime_local, Day_local, Month_local etc. 
* In the cpr plankton data upper case "_L" is used for SampleDate_Local, but a lowercase "_l" is used for Year_, Month_ etc.
* In the new indices files, lowercase "_l" is used for Year_, Month_ etc.

**Comment by leonardolaiolo** [comment]
From Claire email:

---
Hi all,

From my recollection and comments on the Product Specifications we had agreed that:

We use SampleTime_Local when there is a timestamp, not just a date
We use SampleDate_Local when there is NO timestamp, i.e. it is just a date.
We use capital L for Local and all capitals for UTC

Please can you check that this is consistent in what is being delivered from the products.

**Comment by leonardolaiolo** [comment]
Fixes applied to CPR products as well
