### ISSUE TITLE
SampleDepth_m versus Depth_m

### ISSUE THREAD

**Issue by clairedavies** [aodn/public-schema#44]
All data relating to the sampling depth should be SampleDepth_m
Depth_m should only be used for referring to water depth, bathymetry.

In “bgc_chemistry_data”, “bgc_pigments_data”, “bgc_picoplankton_data” and “bgc_tss_data”  Depth_m represents the sampling depths, not the stations depth so should be changed to SampleDepth_m.

**Comment by mhidas** [comment]
> Depth_m should only be used for referring to water depth, bathymetry.

While we're at it, when we do refer to water depth, should we call it `WaterDepth_m` to make it more explicit?

**Comment by clairedavies** [comment]
Yes please, good idea to call it WaterDepth_m

**Comment by leonardolaiolo** [comment]
> All data relating to the sampling depth should be SampleDepth_m
Depth_m should only be used for referring to water depth, bathymetry.
 
Depth_m converted to SampleDepth_m for: 
- [x] bgc_chemistry_data
- [x] bgc_pigments_data
- [x] bgc_picoplankton_data
- [x] bgc_tss_data 
- [x] combined_bgc_data
- [x] nrs_depth_binned_ctd_data
- [x] nrs_derived_indices_data (changes required in the SQL generation code but no difference in the final product)

@mhidas 
>While we're at it, when we do refer to water depth, should we call it WaterDepth_m to make it more explicit?

I could not find or remember a product where we show the water depth (bathymetry)?

**Comment by mhidas** [comment]
> I could not find or remember a product where we show the water depth (bathymetry)?

Good question. Maybe we don't. @clairedavies ?

**Comment by clairedavies** [comment]
Nope, you are right, water depth is only in the package.
