### ISSUE TITLE
Add sample volume to pivoted products

### ISSUE THREAD

**Issue by clairedavies** [aodn/public-schema#46]
Add a SampleVolume_m3 column to the BGC zooplankton and CPR zooplankton and phytoplankton products. The volume information is in the raw data files.

The BGC phytoplankton product does not have a single volume per sample as different taxa may be counted at different volume resolutions. We will access this information from the raw CSV on S3 and create a function in planktonr to access it.

**Comment by mhidas** [comment]
It looks to me like it isn't just BGC phyto that has different sample volumes for different taxa. E.g for `bgc_zoop_raw`:
```sql
SELECT trip_code,
       array_agg(DISTINCT sampvol_m3 ORDER BY sampvol_m3) AS volumes
FROM bgc_zoop_raw
GROUP BY trip_code
HAVING count(DISTINCT sampvol_m3) > 1
ORDER BY trip_code
LIMIT 10;
```
| trip\_code | volumes |
| :--- | :--- |
| DAR20130916 | {0.0622,0.1244} |
| DAR20140117\_1950 | {0.0679,0.1357} |
| DAR20140906\_0030 | {0.0679,0.1018} |
| ESP20101013 | {0.3818,0.509} |
| ESP20130725 | {0.1273,0.4454} |
| IIOE20190519 | {0.9897,1.6967} |
| KAI20100112 | {0.707,1.4139} |
| KAI20110223 | {5.6556,11.3112} |
| KAI20140122 | {0.707,0.9897} |
| MAI20090421 | {22.8486,23.0748} |

In total there are 158 trips which have at least two different sample volues.

**Comment by clairedavies** [comment]
Oh yes, I forgot about adult counts - that would be right. So the same solution for BGC zooplankton as for BGC phytoplankton.

**Comment by leonardolaiolo** [comment]
SQL changes fix only CPR products.
BGC products have multiple volumes per trip code.
