### ISSUE TITLE
Rename PhytoAbund_CellsL to PhytoAbundance_CellsL

### ISSUE THREAD

**Issue by mhidas** [aodn/public-schema#48]
[Comment](https://github.com/aodn/public-schema/pull/41#discussion_r838022891) from review of CPR Derived Indices
> OK, so we have used ZoopAbundance_m3, CopeAbundance_m3 so lets us PhytoAbundance_m3 or PhytoAbundance_CellsL- which I know is neither of the options but would be the most consistent approach.

This also needs to be applied to NRS indices for consistency
- [x] update SQL
- [x] update prod specs

**Comment by leonardolaiolo** [comment]
Fixed in this commit on this [PR](https://github.com/aodn/public-schema/pull/49)   
commit: https://github.com/aodn/public-schema/pull/49/commits/8bf4f262169723fc9e63615a9ace077af2bd5f00
