### ISSUE TITLE
Abbreviations used as column headers in BGC Combined table

### ISSUE THREAD

**Issue by clairedavies** [aodn/public-schema#52]
Please use the full names for the chemistry column headers and not abbreviations i.e. Ammonia not NH4
Same for "SiO4_umolL", "PO4_umolL", "NH4_umolL", "NO3_umolL", "N02_umolL"

**Comment by clairedavies** [comment]
ooppss Ammonium not ammonia

Nitrite is also missing and needs adding to the combined product

**Comment by clairedavies** [comment]
Also for the salinity headers you have used _PSU in the indices data and _psu in the combined bgc data. 
Most people are now dropping PSU as a unit, so it might be better to have no unit for salinity as I think that is the direction of the trend. A lot of journals are now insisting on it being removed.

**Comment by clairedavies** [comment]
synechococcus, prochlorococcus and picoeukaryote are abbreviated in the combined bgc data - is there a reason for this, I would prefer that they weren't, best to match the headers as they are supplied in the data files.

**Comment by mhidas** [comment]
> is there a reason for this

Just following the product specifications... (for all products & column names)
If we need to change them, that's fine, but it would be helpful to update the spec too so they remain consistent.

**Comment by leonardolaiolo** [comment]
Fix:
- [x] change `salinity_psu` to `salinity`
- [x] change `NH4_umolL` to `Ammonium_umolL`,  `NO3_umolL` to `Nitrate_umolL` (same for flags)
- [x] add nitrite (#45)
- [x] update combined bgc product specification document consistently
