### ISSUE TITLE
combined BGC data timestamp

### ISSUE THREAD

**Issue by leonardolaiolo** [aodn/public-schema#53]
I open this as a separate issue as came up as a comment from @clairedavies and it is best to fix this in a separate PR.

> The only product that currently doesn't have a timestamp is the combined BGC data as the times are different for the array of samples we show. Although I have had some feedback that a time is required here. Although the samples are taken at different times it seems an indicative time would be useful. Seeing as we are making these changes it would be good if you could please use the earliest timestamp from the chemistry data for each record in this table. So then all the products would be Time and not Date. Let me know if that needs more explanation.

**Comment by leonardolaiolo** [comment]
@clairedavies can you confirm that in the combined BGC table you'd like for every row  the earliest timestamp from the chemistry data to be shown? I did not check yet but if there are pigments, tss or picoplankton sampled at time where chemistry was not, then we'll end up with no time - is this correct?
As you're saying that an indicative time would be useful, can we use the timestamp from the bgc trip table instead, as for all other products?

**Comment by clairedavies** [comment]
OK, we’ll go with timestamp from the bgc trip table instead.

**Comment by clairedavies** [comment]
Actually, that is actually a couple of hours different in some cases, so can we go with bgc_chemistry time, if that is null then the BGC trip time?
Slightly more complicated but I think better.

**Comment by leonardolaiolo** [comment]
@clairedavies 
I started to have a look into it and I think there are few points to be clarified.
- We now show both UTC and Local timestamp for the chemistry, picoplankton, pigments and tss raw tables. These timestamps are the one from the bgc_trip table as there is no UTC time provided for chemistry, picoplankton, pigments and tss.
- If we use timestamps from chemistry we are going to lose all UTC timestamps in the combined BGC as the chemistry table (as well as picoplankton, pigments and tss) does not provide a UTC timestamps.

Thus, if we go with bgc_chemistry time we are going to have no UTC time values. What do you think?

**Comment by clairedavies** [comment]
OK, I'll provide the UTC time stamps for all those products as well. Then we can have the most applicable timestamp with each sample. The sampling takes about 4 hours, so it isn't good enough to use the trip timestamp for all the samples. This means that I will have to update all the tables, Steve will have to make the modifications to geoserver as will you at your end. I guess we wrote the specifications thinking that AODN were going to do this step and I didn't anticipate this when we decided I would do it. I hadn't clicked you were using trip timestamp for everything.

**Comment by clairedavies** [comment]
Change of plan. Jase and I have discussed this further and because time conversions are so easy to code we have decided that UTC time is not necessary for the BGC products. It can stay in the BGC_trip table as it is there already, and this can be used for the plankton products. However, for chemistry, tss, pico etc. please use the local timestamp that comes with the data. For the BGC combined product, use the chemistry time, if this is null then the trip time is OK. UTC column can be removed for these products.

**Comment by leonardolaiolo** [comment]
@clairedavies okay that sounds good. 
Last thing. Are you sure you want to pick the bgc trip time if the chemistry time time is null? Because we could pick instead the tss, pico or pigments time, I just thought this would make more sense?

**Comment by clairedavies** [comment]
Yes true, pigments is probably the most reliable as pico can be delayed more in analaysis.

**Comment by leonardolaiolo** [comment]
Tasks:
- [ ] update to use only the local timestamp that comes with the data for chemistry, tss, picoplankton and pigments
- [ ] update BGC combined product to use chemistry time, if this is null then pigments then trip time as last

**Comment by clairedavies** [comment]
Does the blue tick mean you have done task 1? It is not visible to us yet through what we access from the geoserver. We are expecting a SampleTime_Local column.

**Comment by leonardolaiolo** [comment]
No it is in only a branch but merged to master. Thus, not in production.

**Comment by clairedavies** [comment]
Any chance we can push a few of these changes through, even if we are still awaiting other actions, as we keep having to code fixes for things that are only temporary?

Thanks,
c

**Comment by leonardolaiolo** [comment]
Sorry that at this stage you have to work around this @clairedavies. Unfortunately I don't think we can push these changes yet. Specifically, these changes in the timestamp affect the Geoserver layers filters, so if we push these changes to master Geoserver is going to break and you'll not be able to get any data.
Furthermore, I just tried few minutes ago to re-harvest the data this morning from your Geoserver and I still have lots of trip_code not in the bgc_trip table - so would be not possible to re run the CSV harvester anyway (only with old files I saved on my local machine).

**Comment by leonardolaiolo** [comment]
Claire email
That sounds good leo, as you suggest.

Also, BGC_trips should be good tomorrow. When we added some of the other projects, duplicates were appearing and Steve was filtering them out but the message wasn’t getting back to me. Hopefully this is good to go now. It is all getting very complicated.

Claire
