### ISSUE TITLE
Parameters violating not-null constraint

### ISSUE THREAD

**Issue by leonardolaiolo** [aodn/public-schema#54]
Some of the new data that came through, as today (25-05-2022), are violating not-null constraint: 

**- bgc_chemistry:** some of the trip codes with `LOR` are missing sample depth (e.g., LOR20200730_102.100.100/138997)
**- bgc_picoplankton_meta:** all the trip codes with `BAI`, `CTL`, `DBI`, `FLB` and `GNI` are missing the replicate number (e.g., BAI20201022_102.100.100/138750 , CTL20200714_102.100.100/138839 ; DBI20200715_102.100.100/138846 ; FLB20200715_102.100.100/138858 ;  20200713_102.100.100/138828)

**Comment by clairedavies** [comment]
bgc_picoplankton_meta - there is no replicate number for those samples, this column can be nullable
bgc_chemistry - we don't have the depth for those samples, we are waiting to see if the samplers recorded them or not. If they didn't record them, then they will have no depth.

**Comment by leonardolaiolo** [comment]
bgc_picoplankton_meta - 
solution: we can update the yaml file so things should not break at out end.
bgc_chemistry - 
solution 1: we can update the yaml file but this mean no depth will be shown in the raw product or combined bgc product.
solution 2: if we know a nominal depth at which these data is usually sampled you could hard code it at your end?
@clairedavies?

**Comment by clairedavies** [comment]
Lets wait on the depth to see what the samplers say, they are in the field this week and aren't contactable. Hopefully we get at least a nominal depth.

**Comment by leonardolaiolo** [comment]
@clairedavies unfortuantely I've run into a new issues that complicate things a bit.
bgc_chemistry  - SAMPLEDEPTH_M is a primary key, when we modify this we end up with duplicate TRIP_CODE so we cannot just make this parameter nullable
bgc_picoplankton_meta - REPLICATE is a primary key for this table.

Therefore, I think some changes may be required at your end? 
Even if there are no REPLICATE for bgc_picoplankton_meta maybe a `1` instead of a `null` would solve the problem?
And for bgc_chemistry let's wait and see what the samplers say, as you say hopefully they'll have at least a nominal depth, otherwise I struggle to understand how users can use these data without knowing where in the water column were sampled!

**Comment by clairedavies** [comment]
Replicate now 1 when there is no value - fixed
I have removed the data from bgc_chemistry where sampledepth_m is null so that you can continue. Hopefully we get a nominal value we can work with - temp fix
