### ISSUE TITLE
Inconsistencies between trip_code in bgc_trip and bgc_picoplankton

### ISSUE THREAD

**Issue by leonardolaiolo** [aodn/public-schema#58]
@clairedavies - sorry I have a feeling this could be quite a bit of a pain..
Coastal trip codes in the `bgc_trip` table are not consistent with trip codes in the `bgc_picoplankton` or trip codes in the `bgc_picoplankton_meta`. Because we join these tables with the `bgc_trip` table to include other required parameters trip_code have to be consistent to be successfully joined. 
This seems related to Coastal Stations data only. As a consequence, this does not break things, but Coastal data are not downloadable from the portal because excluded from the JOIN between `bgc_trip` and `bgc_picoplankton`.
Is there anything that can be does at your end to fix this? I think trip_code consistencies across tables is quite significant for us.

**Comment by clairedavies** [comment]
I forced a refresh of the BGC table, should come through tomorrow, not sure why that didn't refresh automatically.

**Comment by leonardolaiolo** [comment]
@clairedavies I think your bgc_trip table still does not refresh automatically. I tried to get data today 14/06/2022 and some of the trip code are missing from the bgc_trip table (e.g., `YON20140220`, `NSI20091006', 'NSI20091015' ...)

**Comment by clairedavies** [comment]
Should be now, fingers crossed
