### ISSUE TITLE
Interpretation of plankton changelog tables

### ISSUE THREAD

**Issue by mhidas** [aodn/public-schema#8]
I just want to confirm that my understanding of the changelog tables is correct when creating the plankton products.

I'm currently looking at the phytoplankton Genus product. The [code](https://github.com/PlanktonTeam/IMOS_Toolbox/blob/a3d3540d3902d650d6724eef84d85fbc9195d467/Plankton/deprecated/IMOS_Plankton_functions.R#L101) starts by splitting the list of changelog entries into rows where the genus is unchanged from `ParentName` to `TaxonName`, and those where the genus changes:

```r
  # Check genus are effected by change log
  nrslg <- NRSPcl %>% 
    mutate(genus1 = stringr::word(TaxonName, 1),
           genus2 = stringr::word(ParentName, 1)) %>%
    mutate(same = ifelse(genus1==genus2, "yes", "no")) %>%
    filter(same == "no")# no changes at genera level
```

In the `bgc_phyto_changelog` I currently see 38 cases where the `genus1==genus2` and one single case where they are different.

For all the rest (2450 rows), the comparison is undefined because `ParentName` is null. My guess is these can be treated the same way as the "**genus unchanged**" group. Is this correct?

**Comment by clairedavies** [comment]
There won't be as many genera affected by the change log as there will be species.
If the parent names genus is the same as the taxon genus or null then there is no change and these can be treated as genus unchanged. 

The product would be neater if you can assign NA where I have assigned -999. I had to do this as I couldn't work out how to distinguish between 0's and NAs during the pivot process, but you may be able to do this without issue. Users would prefer the output to be in NA's and 0's and values. No big deal but see how you go.

**Comment by mhidas** [comment]
@clairedavies  :+1: Great, thanks for the clarification.

**Comment by mhidas** [comment]
> The product would be neater if you can assign NA where I have assigned -999.

In the final output CSV, NA/null values would be represented by an empty cell. Is that ok?

**Comment by mhidas** [comment]
> There won't be as many genera affected by the change log

That makes sense. There is currently only one 
| TaxonName | StartDate | ParentName |
| :--- | :--- | :--- |
| Phaeocystis spp. \(solitary\) | 2012-08-07 | Unid dinoflagellate &lt; 10 µm |

... and I think even this one will have no effect on the genus product. The earliest sample where this `TaxonName` appears is in 2014, so well after after the `StartDate`.

**Comment by mhidas** [comment]
Ah, hang on, I'm just working this out. This is exactly where it _will_ have an effect!

What this means is that for the genus "Phaeocystis" I actually need to add an entry for every trip before 2012-08-07 with a null/-999. for the Cell_L value?
Is that right?

**Comment by clairedavies** [comment]
> 
> 
> > The product would be neater if you can assign NA where I have assigned -999.
> 
> In the final output CSV, NA/null values would most easily be represented by an empty cell. Is that ok?

Yes. I think so

**Comment by mhidas** [comment]
Ok, here's my first cut at the genus product (based on latest raw data from CSIRO geoserver):
[bgc_phytoplankton_abundance_genus_data.csv](https://github.com/aodn/public-schema/files/7045111/bgc_phytoplankton_abundance_genus_data.csv)

Let me know what you think.

**Comment by mhidas** [comment]
Ok, next question. I'm looking at the Species level product now (phytoplankton abundance).

The [code](https://github.com/PlanktonTeam/IMOS_Toolbox/blob/a3d3540d3902d650d6724eef84d85fbc9195d467/Plankton/deprecated/IMOS_Plankton_functions.R#L180) starts by replacing the original `TaxonName` values in the raw data with just `Genus` + `Species` separated by a space:

```r
  NRSSpecP1 <- NRSPdat %>% 
    mutate(TaxonName = paste0(Genus, ' ', Species)) %>% # remove comments about with flagellates or cilliates etc.
    filter(!TaxonName %in% levels(as.factor(nrsls$TaxonName))
           & Species != "spp." & !is.na(Species) & !grepl("cf.", Species) & !grepl("/", Species)) %>% 
```

I understand this is done to get rid of some additional info in the `TaxonName` that is not relevant at this level. However, it is this new "simplified" `TaxonName` that is then compared to the entries in the changelog. Is that correct?

I just wonder if this might have some occasional unwanted effects, in particular when the `genus` contains more than one word. E.g. 

| genus | species | taxon\_name | parent\_name |
| :--- | :--- | :--- | :--- |
| Tripos \(Amphiceratium\) | biceps | Tripos biceps | Tripos spp. |
| Tripos \(Amphiceratium\) | contortus var. karstenii | Tripos contortus var. karstenii | NULL |
| Tripos \(Amphiceratium\) | falcatus | Tripos falcatus | NULL |
| Tripos \(Amphiceratium\) | fusus | Tripos fusus | NULL |
| Tripos \(Amphiceratium\) | fusus type | Tripos fusus type | NULL |
| Tripos \(Amphiceratium\) | longirostrus | Tripos longirostrus | NULL |

Here the simplified `TaxonName`s for the first row will be "Tripos (Amphiceratium) biceps", which will not match any entry in the changelog. Is this a problem, or am I missing something?

**Comment by mhidas** [comment]
A few other cases where the "simplified" `TaxonName` is doesn't match any entries in the changelog (the third column is the actual taxon name recorded in the raw data):
| Genus | Species | TaxonName |
| :--- | :--- | :--- |
| Cerataulina | compacta | Cerataulina bicornis |
| Meuniera | meuniera | Meuniera membranacea |
| Nitzschia | closterium | Nitzschia closterium - INVALID use Ceratoneis closterium |
| Pseudo-nitzschia | delicatissima complex | Pseudo-nitzschia delicatissima complex &lt;=3 µm |
| Pseudo-nitzschia | seriata complex | Pseudo-nitzschia seriata complex &gt;3 µm |
| Synedra | undulata | Toxarium undulatum |


(Extracted using this query:
```sql
SELECT DISTINCT genus,
                species,
                r.taxon_name
FROM bgc_phyto_raw r LEFT JOIN bgc_phyto_changelog c
                               ON r.genus || ' ' || r.species = c.taxon_name
WHERE species IS NOT NULL AND
      species != 'spp.' AND
      species NOT LIKE '%cf.%' AND
      species NOT LIKE '%/%' AND
      genus NOT LIKE '%(%' AND
      c.taxon_name IS NULL
ORDER BY genus, species, r.taxon_name;
```

**Comment by clairedavies** [comment]
OK so the Tripos subgenera I removed a few days ago as it causes issues with coding and it isn't really used. This hasn't filtered through into the materialised view yet, so I will make sure that Steve updates that. 
Cerataulina, Synedra and Meuniera were all incomplete name changes, I have fixed these and they should disappear off the list (again once the changes filter through).
Nitzschia closterium, as indicated is a name we are not allowed to use, but as it is ingrained in people to use it, I have to leave this here as a reminder.  I have removed the incidences I missed from the raw data file, so should drop out in the query.
Pseudo-nitzschia I have changed so the size is in the species column as well, although this didn't matter in my script as it hasn't changed over time so would be with the non change log data. 
I'll let you know when you should be able to access the updated data.

**Comment by clairedavies** [comment]
Sorry I missed a point there - Pseudo-nitzschia should be excluded from this product as it is a complex and not a species, so when you exclude spp., cf. etc. exclude complex as well.

**Comment by mhidas** [comment]
Ok, I'll keep downloading the data daily so the updates come through when they happen.

I just wanted to confirm that it is correct to do the join by comparing `Genus`+`Species` in the raw data to `TaxonName` in the changelog? (as opposed to using the full `TaxonName` in both tables, which also matches up every row...)

> so when you exclude spp., cf. etc. exclude complex as well

Will do (though it isn't in the R code I've been looking at).

**Comment by mhidas** [comment]
Ok, some updates have come through, and some of the above cases have gone away. However, we still have 34 cases where `Genus`+(space)+`Species` does not match any `TaxonName` in the changelog:

| Genus | Species | TaxonName |
| :--- | :--- | :--- |
| Chaetoceros \(Hyalochaete\) | affinis | Chaetoceros affinis |
| Chaetoceros \(Hyalochaete\) | anastomosans | Chaetoceros anastomosans |
| Chaetoceros \(Hyalochaete\) | compressus | Chaetoceros compressus |
| Chaetoceros \(Hyalochaete\) | curvisetus | Chaetoceros curvisetus |
| Chaetoceros \(Hyalochaete\) | debilis | Chaetoceros debilis |
| Chaetoceros \(Hyalochaete\) | decipiens | Chaetoceros decipiens &lt; 15 µm cell width |
| Chaetoceros \(Hyalochaete\) | decipiens | Chaetoceros decipiens &gt; 15 µm cell width |
| Chaetoceros \(Hyalochaete\) | didymus | Chaetoceros didymus |
| Chaetoceros \(Hyalochaete\) | laeve | Chaetoceros laeve |
| Chaetoceros \(Hyalochaete\) | lorenzianus | Chaetoceros lorenzianus |
| Chaetoceros \(Hyalochaete\) | messanense | Chaetoceros messanense |
| Chaetoceros \(Hyalochaete\) | minimus | Chaetoceros minimus |
| Chaetoceros \(Hyalochaete\) | neglectus | Chaetoceros neglectus |
| Chaetoceros \(Hyalochaete\) | radicans | Chaetoceros radicans |
| Chaetoceros \(Hyalochaete\) | similis | Chaetoceros similis |
| Chaetoceros \(Hyalochaete\) | simplex | Chaetoceros simplex |
| Chaetoceros \(Hyalochaete\) | socialis | Chaetoceros socialis |
| Chaetoceros \(Hyalochaete\) | subtilis | Chaetoceros subtilis |
| Chaetoceros \(Phaeoceros\) | aequatorialis | Chaetoceros aequatorialis |
| Chaetoceros \(Phaeoceros\) | atlanticus | Chaetoceros atlanticus |
| Chaetoceros \(Phaeoceros\) | coarctatus | Chaetoceros coarctatus |
| Chaetoceros \(Phaeoceros\) | coarctatus | Chaetoceros coarctatus \(+ciliates\) |
| Chaetoceros \(Phaeoceros\) | concavicornis | Chaetoceros concavicornis |
| Chaetoceros \(Phaeoceros\) | convolutus | Chaetoceros convolutus |
| Chaetoceros \(Phaeoceros\) | criophilus | Chaetoceros criophilus |
| Chaetoceros \(Phaeoceros\) | danicus | Chaetoceros danicus |
| Chaetoceros \(Phaeoceros\) | densus | Chaetoceros densus |
| Chaetoceros \(Phaeoceros\) | dichaeta | Chaetoceros dichaetus |
| Chaetoceros \(Phaeoceros\) | eibenii | Chaetoceros eibenii |
| Chaetoceros \(Phaeoceros\) | peruvianus | Chaetoceros peruvianus &lt; 40 µm cell width |
| Chaetoceros \(Phaeoceros\) | peruvianus | Chaetoceros peruvianus &gt; 40 µm cell width |
| Chaetoceros \(Phaeoceros\) | rostratus | Chaetoceros rostratus |
| Synedra | undulata | Synedra undulatum |
| Tripos | pentagonus var. tenerus | Tripos pentagonus var.tenerus |

**Comment by clairedavies** [comment]
Sorted, changes should come through in time, maybe not all at once as I refreshed before I finished. Subgenera will now be in the info tables.  Trying to please too many people at once by including it, but it isn't working, so it will be separate in the info tables but still available to the one person who wants it!

**Comment by mhidas** [comment]
:+1: Thanks Claire!

**Comment by mhidas** [comment]
This discussion has served its purpose and can now be closed.
