### ISSUE TITLE
Add sample depth columns for BGC products

### ISSUE THREAD

**Issue by mhidas** [aodn/public-schema#9]
This was mentioned in our catch-up on 2021-08-11.

The plankton products should have a 'SampleDepth_m' column. This information was added to the raw data in #6, but has not yet been added to the products themselves.

**Comment by clairedavies** [comment]
There are a range of depths per trip that the samples are collected at. This means that for each trip there are several rows with different depths. The parameters, columns, will be null if that depth is not applicable and a value if it is. The depth also includes 'WC and is therefore a character and not a number.

**Comment by mhidas** [comment]
Depth columns have been added to all the products
